# Generated by Django 3.0.3 on 2020-09-13 14:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(default='', max_length=50)),
                ('topic', ckeditor_uploader.fields.RichTextUploadingField()),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('afternoon', 'Afternoon')], max_length=25)),
                ('room_capacity', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
