# Generated by Django 3.0.3 on 2020-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200913_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.CharField(choices=[('morning', 'Morning'), ('midmorning', 'Midmorning'), ('afternoon', 'Afternoon')], max_length=25),
        ),
    ]
