# Generated by Django 3.0.3 on 2020-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200915_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
