# Generated by Django 3.0.3 on 2020-09-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='time',
            new_name='schedule',
        ),
    ]
