# Generated by Django 3.0.6 on 2020-09-17 23:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200916_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='topic',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
