# Generated by Django 3.0.6 on 2020-09-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200922_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event',
            new_name='title',
        ),
    ]
