# Generated by Django 3.0.3 on 2020-09-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200913_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phone_number',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='ticket_number',
            new_name='ticketnumber',
        ),
    ]
