# Generated by Django 3.0.3 on 2020-09-15 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200913_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('afternoon', 'Afternoon')], default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
