# Generated by Django 3.0.3 on 2020-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time',
            field=models.CharField(choices=[('morning', 'Morning'), ('midmorning', 'Midmorning'), ('afternoon', 'Afternoon')], max_length=25),
        ),
    ]
