# Generated by Django 3.0.6 on 2020-09-22 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200922_1643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0007_auto_20200916_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='register',
            name='ticketnumber',
        ),
        migrations.RemoveField(
            model_name='register',
            name='time',
        ),
        migrations.AddField(
            model_name='register',
            name='Events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
        migrations.AddField(
            model_name='register',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
