# Generated by Django 3.0.6 on 2020-09-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200922_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Events',
            new_name='Program',
        ),
    ]
