# Generated by Django 3.0.6 on 2020-09-22 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0009_auto_20200922_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Program',
            new_name='events',
        ),
        migrations.AlterField(
            model_name='register',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
