# Generated by Django 3.0.6 on 2020-09-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200922_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='User',
            new_name='user',
        ),
    ]
