# Generated by Django 3.0.6 on 2020-09-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20200922_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='events',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
