# Generated by Django 3.0.6 on 2020-09-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0013_auto_20200922_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={},
        ),
        migrations.RenameField(
            model_name='register',
            old_name='pro',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='user',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='register',
            name='phone_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
